# Generated by Django 2.1.7 on 2020-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdnevnik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('cabinet', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='time',
        ),
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Введите время'),
        ),
        migrations.AddField(
            model_name='example',
            name='time',
            field=models.ManyToManyField(to='appdnevnik.Time'),
        ),
        migrations.AddField(
            model_name='day',
            name='examples',
            field=models.ManyToManyField(to='appdnevnik.Example'),
        ),
    ]
