# Generated by Django 2.1.7 on 2020-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdnevnik', '0004_auto_20200620_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='examples',
            field=models.ManyToManyField(blank=True, related_name='day', to='appdnevnik.Example'),
        ),
    ]
